fix: Disable Flatpak support for Fedora 25
This is necessary because the flatpak package provided by Fedora 25
is too old to support adding Flatpak repositories.

The error message when trying to add a Flatpak repository is:
```
error: URI https://dl.flathub.org/repo/summary exceeded maximum size of 10485760 bytes
```